Day 6/glassprediction/glassprediction/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mlapp.urls')),
]

Day 6/glassprediction/mlapp/urls.py
from django.urls import path
from mlapp import views

app_name = 'mlapp'

urlpatterns = [
    path('predict/', views.predict, name='predict'),
    path('result/', views.result, name='result'),
]

Day 6/glassprediction/mlapp/models.py
from django.db import models

# Create your models here.

Day 6/glassprediction/mlapp/views.py
from django.shortcuts import render
from django.template import loader
import joblib

def predict(request):
    return render(request, 'home.html')

def result(request):
    if request.method == 'POST':
        cls = joblib.load('glass.sav')
        lis = []
        lis.append(float(request.POST['RI']))
        lis.append(float(request.POST['Na']))
        lis.append(float(request.POST['Mg']))
        lis.append(float(request.POST['Al']))
        lis.append(float(request.POST['Si']))
        lis.append(float(request.POST['K']))
        lis.append(float(request.POST['Ca']))
        lis.append(float(request.POST['Ba']))
        lis.append(float(request.POST['Fe']))

        print(lis)

        ans = cls.predict([lis])
        return render(request, 'result.html', context={'answer':ans})

    return render(request, 'result.html')

Day 6/glassprediction/mlapp/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Predict</title>
    <style>
        body {
            font-size: 14px;
            font-family: serif;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .btn-group {
            display: flex;
            gap: 24px;
            align-items: center;
            justify-content: stretch;
        }

        .form {
            font-size: 24px;
            background-color: rgb(255, 4, 46);
            color: white;
            font-weight: 700;
            padding: 30px;
            border-radius: 12px;
            margin: 20px;
            display: flex;
            flex-direction: column;
            gap: 24px;
        }
        .form div{
            display: flex;
            justify-content: space-between;
            align-items: center;
            gap: 24px;
            margin: 10px;
        }
        .form div.btn-group{
            display: flex;
            justify-content: center;
            align-items: center;
            gap: 24px;
            
        }
        .form div input{
            padding: 5px;
            font-size: 18px;
        }
        .form div.btn-group input{
            background-color: green;
            color: white;
            border-radius: 12px;
        }
        </style>
</head>

<body>
    <div class="title">
        <h1>This is Home Page</h1>
    </div>
    <div class="form">
        <form action="{% url 'mlapp:result' %}" method="post">
            {% csrf_token %}
            <div><span>RI:</span> <input type="text" name="RI"></div>
            <div><span>Na:</span> <input type="text" name="Na"></div>
            <div><span>Mg:</span> <input type="text" name="Mg"></div>
            <div><span>Al:</span> <input type="text" name="Al"></div>
            <div><span>Si:</span> <input type="text" name="Si"></div>
            <div><span>K:</span> <input type="text" name="K"></div>
            <div><span>Ca:</span> <input type="text" name="Ca"></div>
            <div><span>Ba:</span> <input type="text" name="Ba"></div>
            <div><span>Fe:</span> <input type="text" name="Fe"></div>
            <div class="btn-group">
                <input type="submit" value="Predict">
                <input type="reset" value="Clear">
            </div>
        </form>
    </div>
</body>

</html>

Day 6/glassprediction/mlapp/templates/result.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result</title>
</head>

<body>
    <div>
        {% if answer %}
        <h1>Glass Type is {{answer}}</h1>
        <p>
            Type of glass: (class attribute)<br>
            -- 1 building_windows_float_processed<br>
            -- 2 building_windows_non_float_processed<br>
            -- 3 vehicle_windows_float_processed<br>
            -- 4 vehicle_windows_non_float_processed (none in this database)<br>
            -- 5 containers<br>
            -- 6 tableware<br>
            -- 7 headlamps<br>
        </p>
        {% else %}
        <h1>Result nhi aaya</h1>
        {% endif %}
    </div>
</body>

</html>